<?xml version="1.0"?>

<robot name="quad_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!--robot name="robot_structure" xmlns:xacro="http://ros.org/wiki/xacro"-->

	<!-- Robot adjustable params -->	
	<xacro:property name="l1" value="0.05"/>
	<xacro:property name="l2" value="0.07"/>
	<xacro:property name="l3" value="0.06"/>
	<xacro:property name="body_width" value="0.08"/>
	<xacro:property name="body_length" value="0.15"/>
	<xacro:property name="body_height" value="0.05"/>
	<xacro:property name="leg_distance" value="0.12"/>

	<!-- fixed params -->
	<xacro:property name="base_link_radius" value="0.005"/>
	<xacro:property name="PI" value="3.1415"/>

	<!-- macro -->
	<xacro:macro name="leg" params="parent number left front">

		<joint name="joint1_in_leg${number}" type="continuous">
			<origin xyz="${front*leg_distance/2} ${left*body_width/2} 0" rpy="0 ${PI/2} 0" />
			<parent link="${parent}" />
			<child link="link1_in_leg${number}" />
			<axis xyz="0 0 1" />  <!-- Rotate around x axis -->
		</joint>

		<transmission name="trans1_in_leg${number}">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="joint1_in_leg${number}" hardwareInterface="PositionJointInterface"/>
			<actuator name="servo1_in_leg${number}" hardwareInterface="PositionJointInterface" />
		</transmission>

		<link name="link1_in_leg${number}">
			<visual>
				<origin xyz="0 ${left*l1/2} 0" rpy="${PI/2} 0 0" />  <!-- cylinder place horizontally  -->
				<geometry>
					<cylinder length="${l1}" radius="${base_link_radius}" />
				</geometry>
				<material name="black">
					<color rgba="0.16 0.17 0.15 0.9" />
				</material>
			</visual>
			<collision>
				<origin xyz="0 ${left*l1/2} 0" rpy="${PI/2} 0 0" />  <!-- cylinder place horizontally  -->
				<geometry>
					<cylinder length="${l1}" radius="${base_link_radius}" />
				</geometry>
			</collision>
		</link>

		<joint name="joint2_in_leg${number}" type="continuous">
			<origin xyz="0 ${left*l1} 0" rpy="${-PI/2} 0 0" />
			<parent link="link1_in_leg${number}" />
			<child link="link2_in_leg${number}" />
			<axis xyz="0 0 1" />  <!-- Rotate around y axis -->
		</joint>

		<transmission name="trans2_in_leg${number}">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="joint2_in_leg${number}" hardwareInterface="PositionJointInterface"/>
			<actuator name="servo2_in_leg${number}" hardwareInterface="PositionJointInterface" />
		</transmission>

		<link name="link2_in_leg${number}">
			<visual>
				<origin xyz="${l2/2} 0 0" rpy="0 ${PI/2} 0" />
				<geometry>
					<cylinder length="${l2}" radius="${base_link_radius}" />
				</geometry>
				<material name="black">
					<color rgba="0.16 0.17 0.15 0.9" />
				</material>
			</visual>
			<collision>
				<origin xyz="${l2/2} 0 0" rpy="0 ${PI/2} 0" />
				<geometry>
					<cylinder length="${l2}" radius="${base_link_radius}" />
				</geometry>
			</collision>
		</link>

		<joint name="joint3_in_leg${number}" type="continuous">
			<origin xyz="${l2} 0 0" rpy="0 0 0" />
			<parent link="link2_in_leg${number}" />
			<child link="link3_in_leg${number}" />
			<axis xyz="0 0 1" />  <!-- Rotate around y axis -->
		</joint>

		<transmission name="trans3_in_leg${number}">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="joint3_in_leg${number}" hardwareInterface="PositionJointInterface"/>
			<actuator name="servo3_in_leg${number}" hardwareInterface="PositionJointInterface" />
		</transmission>

		<link name="link3_in_leg${number}">
			<visual>
				<origin xyz="${l3/2} 0 0" rpy="0 ${PI/2} 0" />
				<geometry>
					<cylinder length="${l3}" radius="${base_link_radius}" />
				</geometry>
				<material name="black">
					<color rgba="0.16 0.17 0.15 0.9" />
				</material>
			</visual>
			<collision>
				<origin xyz="${l3/2} 0 0" rpy="0 ${PI/2} 0" />
				<geometry>
					<cylinder length="${l3}" radius="${base_link_radius}" />
				</geometry>
			</collision>
		</link>
	</xacro:macro>

	<!-- base link -->
	<link name="body">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${body_length} ${body_width} ${body_height}" />
			</geometry>
			<material name="black">
				<color rgba="0.16 0.17 0.15 0.9" />
			</material>	
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${body_length} ${body_width} ${body_height}" />
			</geometry>
		</collision>
	</link>

	<xacro:leg parent="body" number="1" left="1" front="1" />
	<xacro:leg parent="body" number="2" left="1" front="-1" />
	<xacro:leg parent="body" number="3" left="-1" front="1" />
	<xacro:leg parent="body" number="4" left="-1" front="-1" />
	
	<gazebo>
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>/quad_robot</robotNamespace>
		</plugin>
	</gazebo>

</robot>
